apiVersion: v1
kind: ConfigMap
metadata:
  name: bhagwati-config
  namespace: bhagwati-ns
data:
  application.properties: |
    spring.data.mongodb.uri : mongodb://myuser:mypassword@my-mongo-mongodb.default.svc.cluster.local:27017/bhagwatiElec?authSource=bhagwatiElec
    spring.servlet.multipart.max-file-size=10MB
    spring.servlet.multipart.max-request-size=40MB
    spring.data.mongodb.auto-index-creation=false
    spring.servlet.multipart.enabled=true